--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3 (Ubuntu 16.3-1.pgdg22.04+1)
-- Dumped by pg_dump version 16.3 (Ubuntu 16.3-1.pgdg22.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: andrea
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO andrea;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: andrea
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: andrea
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO andrea;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: andrea
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: andrea
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO andrea;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: andrea
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: andrea
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO andrea;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: andrea
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO andrea;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: andrea
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: andrea
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: andrea
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO andrea;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: andrea
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: caricamentoDati_customuser; Type: TABLE; Schema: public; Owner: andrea
--

CREATE TABLE public."caricamentoDati_customuser" (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    codice_fiscale character varying(16)
);


ALTER TABLE public."caricamentoDati_customuser" OWNER TO andrea;

--
-- Name: caricamentoDati_customuser_groups; Type: TABLE; Schema: public; Owner: andrea
--

CREATE TABLE public."caricamentoDati_customuser_groups" (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public."caricamentoDati_customuser_groups" OWNER TO andrea;

--
-- Name: caricamentoDati_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: andrea
--

ALTER TABLE public."caricamentoDati_customuser_groups" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."caricamentoDati_customuser_groups_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: caricamentoDati_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: andrea
--

ALTER TABLE public."caricamentoDati_customuser" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."caricamentoDati_customuser_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: caricamentoDati_customuser_user_permissions; Type: TABLE; Schema: public; Owner: andrea
--

CREATE TABLE public."caricamentoDati_customuser_user_permissions" (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public."caricamentoDati_customuser_user_permissions" OWNER TO andrea;

--
-- Name: caricamentoDati_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: andrea
--

ALTER TABLE public."caricamentoDati_customuser_user_permissions" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."caricamentoDati_customuser_user_permissions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: caricamentoDati_docente; Type: TABLE; Schema: public; Owner: andrea
--

CREATE TABLE public."caricamentoDati_docente" (
    "codiceFiscale" character varying(16) NOT NULL,
    cognome_nome character varying(100) NOT NULL
);


ALTER TABLE public."caricamentoDati_docente" OWNER TO andrea;

--
-- Name: caricamentoDati_pubblicazionepresentata; Type: TABLE; Schema: public; Owner: andrea
--

CREATE TABLE public."caricamentoDati_pubblicazionepresentata" (
    handle character varying(60) NOT NULL,
    issn_isbn character varying(30),
    anno_pubblicazione integer NOT NULL,
    doi character varying(60),
    titolo character varying(500) NOT NULL,
    tipologia_collezione character varying(500) NOT NULL,
    titolo_rivista_atti character varying(500),
    indicizzato_scopus boolean NOT NULL,
    miglior_quartile integer NOT NULL,
    num_coautori_dip integer NOT NULL,
    valutazione_id character varying(100),
    slug character varying(500),
    CONSTRAINT "caricamentoDati_pubblicazionepresentata_num_coautori_dip_check" CHECK ((num_coautori_dip >= 0))
);


ALTER TABLE public."caricamentoDati_pubblicazionepresentata" OWNER TO andrea;

--
-- Name: caricamentoDati_relazionedocentepubblicazione; Type: TABLE; Schema: public; Owner: andrea
--

CREATE TABLE public."caricamentoDati_relazionedocentepubblicazione" (
    id bigint NOT NULL,
    scelta integer,
    autore_id character varying(16) NOT NULL,
    pubblicazione_id character varying(60) NOT NULL
);


ALTER TABLE public."caricamentoDati_relazionedocentepubblicazione" OWNER TO andrea;

--
-- Name: caricamentoDati_relazionedocentepubblicazione_id_seq; Type: SEQUENCE; Schema: public; Owner: andrea
--

ALTER TABLE public."caricamentoDati_relazionedocentepubblicazione" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."caricamentoDati_relazionedocentepubblicazione_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: caricamentoDati_rivistaeccellente; Type: TABLE; Schema: public; Owner: andrea
--

CREATE TABLE public."caricamentoDati_rivistaeccellente" (
    id bigint NOT NULL,
    issn1 character varying(60),
    nome character varying(60) NOT NULL,
    link character varying(300) NOT NULL,
    valutazione_id character varying(100) NOT NULL,
    issn2 character varying(60)
);


ALTER TABLE public."caricamentoDati_rivistaeccellente" OWNER TO andrea;

--
-- Name: caricamentoDati_rivistaeccellente_id_seq; Type: SEQUENCE; Schema: public; Owner: andrea
--

ALTER TABLE public."caricamentoDati_rivistaeccellente" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."caricamentoDati_rivistaeccellente_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: caricamentoDati_valutazione; Type: TABLE; Schema: public; Owner: andrea
--

CREATE TABLE public."caricamentoDati_valutazione" (
    nome character varying(100) NOT NULL,
    anno integer NOT NULL,
    "dataCaricamento" date,
    status character varying(50) NOT NULL,
    "numeroPubblicazioni" integer NOT NULL,
    "dataCaricamentoPubblicazioni" date,
    CONSTRAINT "caricamentoDati_valutazione_numeroPubblicazioni_check" CHECK (("numeroPubblicazioni" >= 0))
);


ALTER TABLE public."caricamentoDati_valutazione" OWNER TO andrea;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: andrea
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO andrea;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: andrea
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: andrea
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO andrea;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: andrea
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: andrea
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO andrea;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: andrea
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: andrea
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO andrea;

--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: caricamentoDati_customuser_groups caricamentoDati_customus_customuser_id_group_id_6407e05b_uniq; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public."caricamentoDati_customuser_groups"
    ADD CONSTRAINT "caricamentoDati_customus_customuser_id_group_id_6407e05b_uniq" UNIQUE (customuser_id, group_id);


--
-- Name: caricamentoDati_customuser_user_permissions caricamentoDati_customus_customuser_id_permission_52e30546_uniq; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public."caricamentoDati_customuser_user_permissions"
    ADD CONSTRAINT "caricamentoDati_customus_customuser_id_permission_52e30546_uniq" UNIQUE (customuser_id, permission_id);


--
-- Name: caricamentoDati_customuser_groups caricamentoDati_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public."caricamentoDati_customuser_groups"
    ADD CONSTRAINT "caricamentoDati_customuser_groups_pkey" PRIMARY KEY (id);


--
-- Name: caricamentoDati_customuser caricamentoDati_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public."caricamentoDati_customuser"
    ADD CONSTRAINT "caricamentoDati_customuser_pkey" PRIMARY KEY (id);


--
-- Name: caricamentoDati_customuser_user_permissions caricamentoDati_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public."caricamentoDati_customuser_user_permissions"
    ADD CONSTRAINT "caricamentoDati_customuser_user_permissions_pkey" PRIMARY KEY (id);


--
-- Name: caricamentoDati_customuser caricamentoDati_customuser_username_key; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public."caricamentoDati_customuser"
    ADD CONSTRAINT "caricamentoDati_customuser_username_key" UNIQUE (username);


--
-- Name: caricamentoDati_docente caricamentoDati_docente_pkey; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public."caricamentoDati_docente"
    ADD CONSTRAINT "caricamentoDati_docente_pkey" PRIMARY KEY ("codiceFiscale");


--
-- Name: caricamentoDati_pubblicazionepresentata caricamentoDati_pubblicazionepresentata_pkey; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public."caricamentoDati_pubblicazionepresentata"
    ADD CONSTRAINT "caricamentoDati_pubblicazionepresentata_pkey" PRIMARY KEY (handle);


--
-- Name: caricamentoDati_relazionedocentepubblicazione caricamentoDati_relazionedocentepubblicazione_pkey; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public."caricamentoDati_relazionedocentepubblicazione"
    ADD CONSTRAINT "caricamentoDati_relazionedocentepubblicazione_pkey" PRIMARY KEY (id);


--
-- Name: caricamentoDati_rivistaeccellente caricamentoDati_rivistaeccellente_pkey; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public."caricamentoDati_rivistaeccellente"
    ADD CONSTRAINT "caricamentoDati_rivistaeccellente_pkey" PRIMARY KEY (id);


--
-- Name: caricamentoDati_valutazione caricamentoDati_valutazione_pkey; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public."caricamentoDati_valutazione"
    ADD CONSTRAINT "caricamentoDati_valutazione_pkey" PRIMARY KEY (nome);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: caricamentoDati_customuser_customuser_id_462277a4; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX "caricamentoDati_customuser_customuser_id_462277a4" ON public."caricamentoDati_customuser_user_permissions" USING btree (customuser_id);


--
-- Name: caricamentoDati_customuser_groups_customuser_id_e8e8c6ea; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX "caricamentoDati_customuser_groups_customuser_id_e8e8c6ea" ON public."caricamentoDati_customuser_groups" USING btree (customuser_id);


--
-- Name: caricamentoDati_customuser_groups_group_id_42ada72b; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX "caricamentoDati_customuser_groups_group_id_42ada72b" ON public."caricamentoDati_customuser_groups" USING btree (group_id);


--
-- Name: caricamentoDati_customuser_permission_id_990560d5; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX "caricamentoDati_customuser_permission_id_990560d5" ON public."caricamentoDati_customuser_user_permissions" USING btree (permission_id);


--
-- Name: caricamentoDati_customuser_username_39ee4cc5_like; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX "caricamentoDati_customuser_username_39ee4cc5_like" ON public."caricamentoDati_customuser" USING btree (username varchar_pattern_ops);


--
-- Name: caricamentoDati_docente_codiceFiscale_b9cb71ea_like; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX "caricamentoDati_docente_codiceFiscale_b9cb71ea_like" ON public."caricamentoDati_docente" USING btree ("codiceFiscale" varchar_pattern_ops);


--
-- Name: caricamentoDati_pubblica_valutazione_id_da00e4f9_like; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX "caricamentoDati_pubblica_valutazione_id_da00e4f9_like" ON public."caricamentoDati_pubblicazionepresentata" USING btree (valutazione_id varchar_pattern_ops);


--
-- Name: caricamentoDati_pubblicazionepresentata_handle_784fd689_like; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX "caricamentoDati_pubblicazionepresentata_handle_784fd689_like" ON public."caricamentoDati_pubblicazionepresentata" USING btree (handle varchar_pattern_ops);


--
-- Name: caricamentoDati_pubblicazionepresentata_slug_4be3cd9d; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX "caricamentoDati_pubblicazionepresentata_slug_4be3cd9d" ON public."caricamentoDati_pubblicazionepresentata" USING btree (slug);


--
-- Name: caricamentoDati_pubblicazionepresentata_slug_4be3cd9d_like; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX "caricamentoDati_pubblicazionepresentata_slug_4be3cd9d_like" ON public."caricamentoDati_pubblicazionepresentata" USING btree (slug varchar_pattern_ops);


--
-- Name: caricamentoDati_pubblicazionepresentata_valutazione_id_da00e4f9; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX "caricamentoDati_pubblicazionepresentata_valutazione_id_da00e4f9" ON public."caricamentoDati_pubblicazionepresentata" USING btree (valutazione_id);


--
-- Name: caricamentoDati_relazion_autore_id_e5ae5283_like; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX "caricamentoDati_relazion_autore_id_e5ae5283_like" ON public."caricamentoDati_relazionedocentepubblicazione" USING btree (autore_id varchar_pattern_ops);


--
-- Name: caricamentoDati_relazion_pubblicazione_id_9c2db4fd_like; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX "caricamentoDati_relazion_pubblicazione_id_9c2db4fd_like" ON public."caricamentoDati_relazionedocentepubblicazione" USING btree (pubblicazione_id varchar_pattern_ops);


--
-- Name: caricamentoDati_relazioned_autore_id_e5ae5283; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX "caricamentoDati_relazioned_autore_id_e5ae5283" ON public."caricamentoDati_relazionedocentepubblicazione" USING btree (autore_id);


--
-- Name: caricamentoDati_relazioned_pubblicazione_id_9c2db4fd; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX "caricamentoDati_relazioned_pubblicazione_id_9c2db4fd" ON public."caricamentoDati_relazionedocentepubblicazione" USING btree (pubblicazione_id);


--
-- Name: caricamentoDati_rivistaeccellente_valutazione_id_37f5bd58; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX "caricamentoDati_rivistaeccellente_valutazione_id_37f5bd58" ON public."caricamentoDati_rivistaeccellente" USING btree (valutazione_id);


--
-- Name: caricamentoDati_rivistaeccellente_valutazione_id_37f5bd58_like; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX "caricamentoDati_rivistaeccellente_valutazione_id_37f5bd58_like" ON public."caricamentoDati_rivistaeccellente" USING btree (valutazione_id varchar_pattern_ops);


--
-- Name: caricamentoDati_valutazione_nome_9001ef8a_like; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX "caricamentoDati_valutazione_nome_9001ef8a_like" ON public."caricamentoDati_valutazione" USING btree (nome varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: andrea
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: caricamentoDati_customuser_user_permissions caricamentoDati_cust_customuser_id_462277a4_fk_caricamen; Type: FK CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public."caricamentoDati_customuser_user_permissions"
    ADD CONSTRAINT "caricamentoDati_cust_customuser_id_462277a4_fk_caricamen" FOREIGN KEY (customuser_id) REFERENCES public."caricamentoDati_customuser"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: caricamentoDati_customuser_groups caricamentoDati_cust_customuser_id_e8e8c6ea_fk_caricamen; Type: FK CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public."caricamentoDati_customuser_groups"
    ADD CONSTRAINT "caricamentoDati_cust_customuser_id_e8e8c6ea_fk_caricamen" FOREIGN KEY (customuser_id) REFERENCES public."caricamentoDati_customuser"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: caricamentoDati_customuser_groups caricamentoDati_cust_group_id_42ada72b_fk_auth_grou; Type: FK CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public."caricamentoDati_customuser_groups"
    ADD CONSTRAINT "caricamentoDati_cust_group_id_42ada72b_fk_auth_grou" FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: caricamentoDati_customuser_user_permissions caricamentoDati_cust_permission_id_990560d5_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public."caricamentoDati_customuser_user_permissions"
    ADD CONSTRAINT "caricamentoDati_cust_permission_id_990560d5_fk_auth_perm" FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: caricamentoDati_pubblicazionepresentata caricamentoDati_pubb_valutazione_id_da00e4f9_fk_caricamen; Type: FK CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public."caricamentoDati_pubblicazionepresentata"
    ADD CONSTRAINT "caricamentoDati_pubb_valutazione_id_da00e4f9_fk_caricamen" FOREIGN KEY (valutazione_id) REFERENCES public."caricamentoDati_valutazione"(nome) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: caricamentoDati_relazionedocentepubblicazione caricamentoDati_rela_autore_id_e5ae5283_fk_caricamen; Type: FK CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public."caricamentoDati_relazionedocentepubblicazione"
    ADD CONSTRAINT "caricamentoDati_rela_autore_id_e5ae5283_fk_caricamen" FOREIGN KEY (autore_id) REFERENCES public."caricamentoDati_docente"("codiceFiscale") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: caricamentoDati_relazionedocentepubblicazione caricamentoDati_relazione_pubblicazione_id_9c2db4fd_fk; Type: FK CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public."caricamentoDati_relazionedocentepubblicazione"
    ADD CONSTRAINT "caricamentoDati_relazione_pubblicazione_id_9c2db4fd_fk" FOREIGN KEY (pubblicazione_id) REFERENCES public."caricamentoDati_pubblicazionepresentata"(handle) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: caricamentoDati_rivistaeccellente caricamentoDati_rivi_valutazione_id_37f5bd58_fk_caricamen; Type: FK CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public."caricamentoDati_rivistaeccellente"
    ADD CONSTRAINT "caricamentoDati_rivi_valutazione_id_37f5bd58_fk_caricamen" FOREIGN KEY (valutazione_id) REFERENCES public."caricamentoDati_valutazione"(nome) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: andrea
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO andrea;


--
-- PostgreSQL database dump complete
--

