# Generated by Django 3.2.12 on 2024-03-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamentoDati', '0002_auto_20240310_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valutazione',
            name='valore',
        ),
        migrations.AddField(
            model_name='valutazione',
            name='status',
            field=models.CharField(choices=[('', 'Vuoto'), ('da_valutare', 'Da valutare'), ('in_fase_di_valutazione', 'In fase di valutazione'), ('terminato', 'Terminato')], default='', max_length=50, verbose_name='status'),
        ),
    ]
