# Generated by Django 3.2.12 on 2024-03-10 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamentoDati', '0003_auto_20240310_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='valutazione',
            name='valore',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='valutazione',
            name='status',
            field=models.CharField(choices=[('vuoto', 'Vuoto'), ('da_valutare', 'Da valutare'), ('in_fase_di_valutazione', 'In fase di valutazione'), ('terminato', 'Terminato')], default='', max_length=50, verbose_name='status'),
        ),
    ]
