# Generated by Django 4.2.13 on 2024-06-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamentoDati', '0003_rename_isbn_rivistaeccellente_issn1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubblicazionepresentata',
            name='doi',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='pubblicazionepresentata',
            name='handle',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rivistaeccellente',
            name='issn1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='rivistaeccellente',
            name='issn2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
