# Generated by Django 4.2.13 on 2024-06-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamentoDati', '0004_alter_pubblicazionepresentata_doi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubblicazionepresentata',
            name='titolo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='rivistaeccellente',
            name='link',
            field=models.CharField(default='_', max_length=300),
        ),
    ]
