# Generated by Django 3.2.12 on 2024-03-10 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamentoDati', '0005_auto_20240310_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valutazione',
            name='numeroPubblicazioni',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='numero di pubblicazioni da selezionare'),
        ),
        migrations.AlterField(
            model_name='valutazione',
            name='status',
            field=models.CharField(choices=[('Vuoto', 'Vuoto'), ('Da Valutare', 'Da valutare'), ('In fase di valutazione', 'In fase di valutazione'), ('Terminato', 'Terminato')], default='Vuoto', max_length=50),
        ),
    ]
