# Generated by Django 3.2.12 on 2024-03-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamentoDati', '0006_auto_20240310_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='valutazione',
            name='dataCaricamentoPubblicazioni',
            field=models.DateField(blank=True, null=True, verbose_name='data di caricamento delle pubblicazioni'),
        ),
    ]
