# Generated by Django 4.2.13 on 2024-06-13 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caricamentoDati', '0006_alter_docente_cognome_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relazionedocentepubblicazione',
            name='autore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caricamentoDati.docente'),
        ),
    ]
