# Generated by Django 4.2.13 on 2024-06-13 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caricamentoDati', '0007_alter_relazionedocentepubblicazione_autore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relazionedocentepubblicazione',
            name='autore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caricamentoDati.docente'),
        ),
    ]
