# Generated by Django 3.2.12 on 2024-03-17 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamentoDati', '0009_alter_valutazione_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubblicazionepresentata',
            name='miglior_quartile',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='miglior quartile'),
        ),
    ]
