# Generated by Django 3.2.12 on 2024-04-29 09:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caricamentoDati', '0010_alter_pubblicazionepresentata_miglior_quartile'),
    ]

    operations = [
        migrations.AddField(
            model_name='rivistaeccellente',
            name='link',
            field=models.CharField(default='_', max_length=200),
        ),
        migrations.AddField(
            model_name='rivistaeccellente',
            name='valutazione',
            field=models.ForeignKey(default='_', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='caricamentoDati.valutazione'),
        ),
        migrations.AlterField(
            model_name='pubblicazionepresentata',
            name='miglior_quartile',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='miglior quartile'),
        ),
        migrations.AlterField(
            model_name='rivistaeccellente',
            name='isbn',
            field=models.CharField(max_length=30),
        ),
    ]
