# Generated by Django 5.0.4 on 2024-04-29 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamentoDati', '0012_alter_rivistaeccellente_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='rivistaeccellente',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rivistaeccellente',
            name='valutazione',
            field=models.ForeignKey(default='_', on_delete=django.db.models.deletion.CASCADE, to='caricamentoDati.valutazione'),
        ),
    ]
